./deploy-hdfs-zookeeper-kafka-and-spark.sh
./create-model.sh
./check-spark-jobs-finished.sh
./generate-messages.sh
./deploy-nifi.sh
./post-deploy-nifi.sh
./deploy-jupyterlab.sh
./post-deploy-jupyterlab.sh
./deploy-edgelb.sh
./update-etc-hosts-for-nifi.sh
./update-nifi-permissions.sh
